server.port=3000

spring.datasource.url=jdbc:postgresql://localhost:5432/demo_dashboard
spring.datasource.username=demo_dashboard_user
spring.datasource.password=demo_dashboard_pass_123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.web.resources.static-locations=classpath:/static/
